/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        arabic: ['Noto Kufi Arabic', 'Tajawal', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'Noto Kufi Arabic', 'system-ui', 'sans-serif'],
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          50: '#f0f9f4',
          100: '#dbf0e3',
          200: '#bae0cc',
          300: '#8cc9ac',
          400: '#5cab88',
          500: '#3a8f6c',
          600: '#297255',
          700: '#215b46',
          800: '#1c4938',
          900: '#183c30',
          950: '#0d231c',
        },
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        holly: {
          50: '#f0f9f4',
          100: '#dbf0e3',
          200: '#bae0cc',
          300: '#8cc9ac',
          400: '#5cab88',
          500: '#3a8f6c',
          600: '#297255',
          700: '#215b46',
          800: '#1c4938',
          900: '#183c30',
          950: '#0d231c',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
          gold: '#d4a853',
          sand: '#e8dcc4',
        },
      },
    },
  },
  plugins: [require('tailwindcss-rtl')],
};
